version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:4000"
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - Personal_network

  myPostgresDb:
    image: postgres
    restart: always
    ports:
      - "5455:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: BenBouiss 
      POSTGRES_DB: visiteur_count
    networks:
      - Personal_network
    
networks:
  Personal_network:
    driver: host
    name: redis_network
    #external: True